from __future__ import annotations

from typing import Protocol, runtime_checkable

from docuflow.documents.models import Document
from docuflow.extraction.models import ExtractionResult
from docuflow.filling.models import FillingResult
from docuflow.observability.traces import Trace


@runtime_checkable
class Storage(Protocol):
    async def save_document(self, document: Document) -> str: ...
    async def save_result(self, result: ExtractionResult) -> str: ...
    async def save_filling_result(self, result: FillingResult) -> str: ...
    async def save_trace(self, trace: Trace) -> str: ...
    async def load_result(self, document_id: str) -> ExtractionResult | None: ...
    async def load_document(self, document_id: str) -> Document | None: ...
    async def list_documents(self) -> list[str]: ...
    async def get_pending_reviews(self) -> list[str]: ...
    async def get_by_status(self, status: str) -> list[str]: ...
